import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class AuditLogError(Exception):
    """Raised when an audit event cannot be recorded."""
    pass


class AuditLogger:
    """
    Records auditable events generated by the AI business
    operations pipeline.

    Audit events are stored as JSON Lines.

    Each line in the audit log represents one event.
    """

    def __init__(
        self,
        log_file: str = "logs/audit.log"
    ):
        self.log_file = Path(log_file)

        # Create the log directory if it does not exist.
        self.log_file.parent.mkdir(
            parents=True,
            exist_ok=True
        )

    def log_event(
        self,
        event_type: str,
        event_data: dict[str, Any]
    ) -> dict[str, Any]:

        if not event_type or not event_type.strip():
            raise AuditLogError(
                "event_type is required."
            )

        if event_data is None:
            raise AuditLogError(
                "event_data is required."
            )

        event = {
            "event_id": self._generate_event_id(),
            "event_type": event_type.strip(),
            "timestamp": (
                datetime.now(
                    timezone.utc
                ).isoformat()
            ),
            "data": event_data
        }

        try:

            with self.log_file.open(
                "a",
                encoding="utf-8"
            ) as file:

                file.write(
                    json.dumps(
                        event,
                        default=str
                    )
                    + "\n"
                )

        except Exception as error:

            raise AuditLogError(
                f"Failed to write audit event: {error}"
            ) from error

        return event

    def _generate_event_id(self) -> str:

        timestamp = datetime.now(
            timezone.utc
        ).strftime(
            "%Y%m%d%H%M%S%f"
        )

        return f"AUDIT-{timestamp}"


if __name__ == "__main__":

    print(
        "\n========== AUDIT LOGGER TEST ==========\n"
    )

    logger = AuditLogger()

    # --------------------------------------
    # Test 1: Analysis completed
    # --------------------------------------

    print(
        "Logging analysis event..."
    )

    analysis_event = logger.log_event(
        event_type="ANALYSIS_COMPLETED",
        event_data={
            "question": (
                "What was the revenue in May 2025?"
            ),
            "workflow": "simple_factual",
            "status": "VERIFIED"
        }
    )

    print(
        analysis_event
    )

    # --------------------------------------
    # Test 2: Recommendation created
    # --------------------------------------

    print(
        "\nLogging recommendation event..."
    )

    recommendation_event = logger.log_event(
        event_type="RECOMMENDATION_CREATED",
        event_data={
            "recommendation_status": (
                "READY_FOR_REVIEW"
            ),
            "recommendation_confidence": (
                "MEDIUM"
            ),
            "human_approval_required": True
        }
    )

    print(
        recommendation_event
    )

    # --------------------------------------
    # Test 3: Approval requested
    # --------------------------------------

    print(
        "\nLogging approval request..."
    )

    approval_event = logger.log_event(
        event_type="APPROVAL_REQUESTED",
        event_data={
            "approval_status": "PENDING",
            "approved_by": None
        }
    )

    print(
        approval_event
    )

    # --------------------------------------
    # Verify log file
    # --------------------------------------

    print(
        "\nAudit log file:"
    )

    print(
        logger.log_file
    )

    print(
        "\nAudit logger test completed."
    )