import json
from pathlib import Path


EVIDENCE_FILE = Path("analytics/investigation_output.json")


class EvidenceIndex:
    """
    Converts investigation evidence into deterministic metric lookups.

    The LLM does not decide what the evidence says.
    This class reads the evidence generated by the analytics pipeline.
    """

    def __init__(self, evidence_file=EVIDENCE_FILE):
        self.evidence_file = evidence_file
        self.evidence = self._load_evidence()
        self.metrics = self._build_index()

    def _load_evidence(self):
        if not self.evidence_file.exists():
            raise FileNotFoundError(
                f"Evidence file not found: {self.evidence_file}"
            )

        with open(self.evidence_file, "r", encoding="utf-8") as file:
            return json.load(file)

    def _build_index(self):
        metrics = {}

        # ---------------------------------------------------------
        # Product evidence
        # ---------------------------------------------------------

        for product in self.evidence["product_evidence"]:
            entity = product["product"]

            metrics[(entity, "revenue")] = {
                "value": product["revenue_change_percentage"],
                "unit": "percentage",
                "direction": self._direction(
                    product["revenue_change_percentage"]
                )
            }

            metrics[(entity, "return")] = {
                "value": product["return_change"],
                "unit": "count",
                "direction": self._direction(
                    product["return_change"]
                )
            }

            metrics[(entity, "support_ticket")] = {
                "value": product["support_ticket_change"],
                "unit": "count",
                "direction": self._direction(
                    product["support_ticket_change"]
                )
            }

            metrics[(entity, "complaint")] = {
                "value": product["complaint_change"],
                "unit": "count",
                "direction": self._direction(
                    product["complaint_change"]
                )
            }

            metrics[(entity, "refund")] = {
                "value": product["refund_change"],
                "unit": "count",
                "direction": self._direction(
                    product["refund_change"]
                )
            }

        # ---------------------------------------------------------
        # Regional evidence
        # ---------------------------------------------------------

        for region in self.evidence["regional_evidence"]:
            entity = region["region"]

            metrics[(entity, "revenue")] = {
                "value": region["revenue_change_percentage"],
                "unit": "percentage",
                "direction": self._direction(
                    region["revenue_change_percentage"]
                )
            }


                    # ---------------------------------------------------------
        # Overall business evidence
        # ---------------------------------------------------------

        return_rate = self.evidence["return_rate"]

        metrics[("Return rate", "return_rate")] = {
            "value": return_rate["change_percentage_points"],
            "unit": "percentage_points",
            "direction": self._direction(
                return_rate["change_percentage_points"]
            )
        }

        support_tickets = self.evidence["support_tickets"]

        metrics[("Support tickets", "support_ticket")] = {
            "value": support_tickets["change"],
            "unit": "count",
            "direction": self._direction(
                support_tickets["change"]
            )
        }

        return metrics

    @staticmethod
    def _direction(value):
        if value > 0:
            return "increased"

        if value < 0:
            return "decreased"

        return "unchanged"

    def get_metric(self, entity, metric):
        """
        Return evidence for a specific entity and metric.
        """

        return self.metrics.get((entity, metric))

    def print_index(self):
        print("\n========== EVIDENCE INDEX ==========\n")

        for (entity, metric), evidence in self.metrics.items():
            print(
                f"{entity} | "
                f"{metric} | "
                f"{evidence['value']} | "
                f"{evidence['unit']} | "
                f"{evidence['direction']}"
            )


if __name__ == "__main__":
    index = EvidenceIndex()
    index.print_index()

    print("\n========== SAMPLE LOOKUP ==========\n")

    result = index.get_metric(
    "Phone X1",
    "return"
)

    print(result)