from typing import List

from ai.claim_schema import BusinessClaim, ClaimStatus


class ValidationReport:
    """
    Summarizes deterministic validation results for an AI analysis.

    This report is generated by Python, not by the LLM.
    """

    def __init__(self, validated_claims: List[BusinessClaim]):

        self.validated_claims = validated_claims

        self.total_claims = len(validated_claims)

        self.supported_count = sum(
            1
            for claim in validated_claims
            if claim.status == ClaimStatus.SUPPORTED
        )

        self.contradicted_count = sum(
            1
            for claim in validated_claims
            if claim.status == ClaimStatus.CONTRADICTED
        )

        self.uncertain_count = sum(
            1
            for claim in validated_claims
            if claim.status == ClaimStatus.UNCERTAIN
        )

    @property
    def validation_passed(self):
        """
        Analysis passes only when no claim is contradicted.

        Uncertain claims do not automatically fail because
        lack of evidence is different from incorrect evidence.
        """

        return (
        self.total_claims > 0
        and self.contradicted_count == 0
    )

    @property
    def validation_rate(self):
        """
        Percentage of claims that are directly supported.
        """

        if self.total_claims == 0:
            return 0.0

        return (
            self.supported_count
            / self.total_claims
        ) * 100

    def get_issues(self):
        """
        Returns claims that need attention.
        """

        issues = []

        for claim in self.validated_claims:

            if claim.status in (
                ClaimStatus.CONTRADICTED,
                ClaimStatus.UNCERTAIN
            ):
                issues.append({
                    "entity": claim.entity,
                    "metric": claim.metric,
                    "status": claim.status.value,
                    "explanation": claim.explanation
                })

        return issues

    def print_report(self):

        print("\n========== VALIDATION REPORT ==========\n")

        print(f"Total claims:       {self.total_claims}")
        print(f"Supported:          {self.supported_count}")
        print(f"Contradicted:       {self.contradicted_count}")
        print(f"Uncertain:          {self.uncertain_count}")

        print(
            f"Validation rate:    "
            f"{self.validation_rate:.2f}%"
        )

        print()

        if self.validation_passed:
            print("Validation status:   PASSED")
        else:
            print("Validation status:   FAILED")

        issues = self.get_issues()

        if issues:

            print("\n========== ISSUES ==========\n")

            for issue in issues:

                print(
                    f"- {issue['entity']} | "
                    f"{issue['metric']} | "
                    f"{issue['status']}"
                )

                print(
                    f"  {issue['explanation']}"
                )

        print()


def main():

    print("\n========== VALIDATION REPORT TEST ==========\n")

    # ---------------------------------------------------------
    # Test claims
    # ---------------------------------------------------------

    supported_claim = BusinessClaim(
        entity="Phone X1",
        metric="revenue",
        direction="increased",
        value=32.96,
        unit="percentage",
        status=ClaimStatus.SUPPORTED,
        explanation="Evidence confirms the claim."
    )

    contradicted_claim = BusinessClaim(
        entity="Phone X2",
        metric="return",
        direction="increased",
        value=5,
        unit="count",
        status=ClaimStatus.CONTRADICTED,
        explanation="Evidence shows the return count decreased."
    )

    uncertain_claim = BusinessClaim(
        entity="Unknown Product",
        metric="return",
        direction="increased",
        value=5,
        unit="count",
        status=ClaimStatus.UNCERTAIN,
        explanation="No evidence found."
    )

    claims = [
        supported_claim,
        contradicted_claim,
        uncertain_claim
    ]

    # ---------------------------------------------------------
    # Create report
    # ---------------------------------------------------------

    report = ValidationReport(claims)

    report.print_report()


if __name__ == "__main__":
    main()